name: "仕様追加・変更・削除"
description: 仕様の追加や変更・削除の提案
title: "[Feature]: "
labels: [ "feature" ]
body:
  - type: textarea
    id: specification-abstract
    attributes:
      label: 仕様について
      description: |
        Youtube　Usability　Appで追加したいこと、変更したいこと、削除したいことを書き込んでください
      placeholder: 概要
    validations:
      required: true
  - type: textarea
    id: specification-description
    attributes:
      label: 詳細
      description: |
        上記の詳細を書き込んでください
      placeholder: 説明
    validations:
      required: true